[package]
name = "commander"
version = "0.1.0"
edition = "2024"

[lib]

[workspace]
resolver = "2"
members = [
    "packages/parser",
    "packages/from_derive",
]

[dependencies]
parser = { path = "packages/parser" }
from_derive = { path = "packages/from_derive" }