[package]
name = "dsl_cli"
version = "0.1.0"
edition = "2024"

[lib]

[workspace]
resolver = "2"
members = [
    "packages/core_lib",
    "packages/cli_macro",
    "packages/common"
]

[dependencies]
cli_macro = { path = "packages/cli_macro" }
core_lib = { path = "packages/core_lib" }
common = { path = "packages/common" }

[[example]]
name = "string_utils"
path = "examples/string_utils.rs"
