[package]
name = "commander"
version = "0.1.0"
edition = "2024"

[lib]

[workspace]
resolver = "2"
members = [
    "packages/parser",
    "packages/args_derive", "packages/opts_derive", "packages/core",
]
default-members = [
    "packages/parser",
    "packages/args_derive",
    "packages/opts_derive",
]

[dependencies]
parser = { path = "packages/parser" }
args_derive = { path = "packages/args_derive" }
opts_derive = { path = "packages/opts_derive" }
core = { path = "packages/core" }
